# Makefile.deps created Tue May 27 12:59:50 PDT 2014
debug.o: debug.c debug.h
stack.o: stack.c stack.h bigint.h debug.h
bigint.o: bigint.c bigint.h
token.o: token.c token.h debug.h
main.o: main.c bigint.h debug.h stack.h token.h
