# Makefile.dep created Mon Jul  6 22:29:29 PDT 2015
commands.o: commands.cpp commands.h inode.h util.h debug.h
debug.o: debug.cpp commands.h inode.h util.h debug.h
inode.o: inode.cpp debug.h inode.h util.h
util.o: util.cpp util.h debug.h
main.o: main.cpp commands.h inode.h util.h debug.h
